name: CD - FAST Tooling Publisher

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * 0-4'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_SERVICE_USER: "Microsoft FAST DevOps"
  GITHUB_SERVICE_EMAIL: "fastsvc@microsoft.com"
      
jobs:
  build_linux:
    runs-on: ubuntu-latest
    if: contains('janechu,williamw2,awentzel,eisenbergeffect', github.actor)

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ env.GITHUB_TOKEN }}

    - name: Add or Update packages
      run: sudo yarn global add lerna

    - name: Set Git User
      run: |
        git config --global user.name "${{ env.GITHUB_SERVICE_USER }}"
        git config --global user.email "${{ env.GITHUB_SERVICE_EMAIL }}"
   
    - name: Install package dependencies / prepare workspaces
      run: npm ci

    - name: Check for the presence of changed files inside ./change
      run: npm run publish:check

    - name: Build
      run: npm run build --if-present

    - name: Test
      run: npm run test --if-present
   
    - name: Publish NPM packages
      env:
        NPM_SECRET_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npm run publish:start-ci -n $NPM_SECRET_TOKEN
    
    - name: send notification message on failure
      if: failure()
      uses: appleboy/discord-action@master
      with:
        webhook_id: ${{ secrets.WEBHOOK_ID }}
        webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
        username: "GitHub Automated notification"
        message: "FAST publishing failed"
